# Generated by Django 4.2.27 on 2025-12-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payouts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payout",
            name="group",
        ),
    ]
